baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Kein Li'
theme = "paper"


[author]
  name = "Kein Li"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  # twitter = 'YOUR_TWITTER_ID'             # twitter.com/YOUR_TWITTER_ID
  github = 'kein-1'                         # github.com/YOUR_GITHUB_ID
  # instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'keinli'             # linkedin.com/in/YOUR_LINKEDIN_ID
  
  rss = true                                # show rss icon

  author = "Kein Li"

  # home page profile
  avatar = 'https://github.com/kein-1.png'
  name = "Kein Li"
  bio = 'Software engineer. Always learning.'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

